// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	int N = 1000;
	int cmpcnt, target, idx;
	vector<int> numbers, copied;
	fillvector(numbers, N);
	copied = numbers;
	print(numbers);

	sort(numbers.begin(), numbers.end());
	target = getTarget(numbers);

	cmpcnt = 0;
	auto start = high_resolution_clock::now();
	idx = LinearSearch(numbers, target, cmpcnt);
	auto stop = high_resolution_clock::now();
	auto duration = duration_cast<nanoseconds>(stop - start);
	REQUIRE(numbers[idx] == target);

	cout << "Found the target " << target << " at the index " << idx << endl;
	cout << "The Linear Search comparison count " << cmpcnt << endl;
	cout << "The elappsed time  " << duration.count() << endl;

	cmpcnt = 0;
	start = high_resolution_clock::now();
	idx = binSearch(numbers, target, cmpcnt);
	stop = high_resolution_clock::now();
	duration = duration_cast<nanoseconds>(stop - start);

	cout << "Found the target " << target << " at the index " << idx << endl;
	cout << "The Binary Search comparison count " << cmpcnt << endl;
	cout << "The elappsed time  " << duration.count() << endl;
	REQUIRE(numbers[idx] == target);
}
